### ISSUE TITLE
Test upload and use of Jupyter notebook

### ISSUE THREAD

**Issue by thomasholmrod** [pan-training/pan-learning-jupyterhub#4]
As a **teacher** I want to upload my own notebook to a course on pan-learning.or so that students can use it for training

As a **student** I want to run a notebook from pan-learning.org which has been uploaded by my teacher

**Comment by moving-northwards** [comment]
As we have now moved away from Illumidesk this has been successfully carried out using a separate JupyterHub deployment for a specific course here: [https://pan-learning.org/moodle/course/view.php?id=70](https://pan-learning.org/moodle/course/view.php?id=70)
It is also discussed in issue [https://github.com/pan-training/pan-learning-jupyterhub/issues/1](https://github.com/pan-training/pan-learning-jupyterhub/issues/1)
